// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/RecognitionServer.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Recognition {
  public static partial class RecognitionServer
  {
    static readonly string __ServiceName = "recognition.RecognitionServer";

    static readonly grpc::Marshaller<global::Recognition.GestureRecognitionRequest> __Marshaller_recognition_GestureRecognitionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Recognition.GestureRecognitionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Recognition.GestureRecognitionReply> __Marshaller_recognition_GestureRecognitionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Recognition.GestureRecognitionReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Recognition.GestureRecognitionRequest, global::Recognition.GestureRecognitionReply> __Method_GestureRecognition = new grpc::Method<global::Recognition.GestureRecognitionRequest, global::Recognition.GestureRecognitionReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GestureRecognition",
        __Marshaller_recognition_GestureRecognitionRequest,
        __Marshaller_recognition_GestureRecognitionReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Recognition.RecognitionServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for RecognitionServer</summary>
    public partial class RecognitionServerClient : grpc::ClientBase<RecognitionServerClient>
    {
      /// <summary>Creates a new client for RecognitionServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RecognitionServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RecognitionServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RecognitionServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RecognitionServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RecognitionServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Recognition.GestureRecognitionRequest, global::Recognition.GestureRecognitionReply> GestureRecognition(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GestureRecognition(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Recognition.GestureRecognitionRequest, global::Recognition.GestureRecognitionReply> GestureRecognition(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GestureRecognition, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RecognitionServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RecognitionServerClient(configuration);
      }
    }

  }
}
#endregion
